"""Add custom fields to user

Revision ID: 4d2a11fd300f
Revises: 948195db1671
Create Date: 2023-09-02 09:47:44.063142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2a11fd300f'
down_revision: Union[str, None] = '948195db1671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_id'), 'city', ['id'], unique=False)
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    gender_enum = sa.Enum('MALE', 'FEMALE', name='genderenum')
    gender_enum.create(op.get_bind())
    op.add_column('user', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('user', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    op.drop_column('user', 'mobile_number')
    op.drop_column('user', 'gender')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_index(op.f('ix_city_id'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
